name: InventoryTweaks
version: 1.3.1
author: IKEA_Jesus
main: dev.w1zzrd.invtweaks.InvTweaksPlugin
api-version: 1.13
commands:
  sort:
    description: Sort chest you are looking at
    usage: /<command>
    permission: invtweaks.sort
  magnet:
    description: Toggle item magnet mode for player
    usage: /<command>
    permission: invtweaks.magnet
  search:
    description: Search for a given item in all nearby inventories
    usage: /<command> {item type}
    permission: invtweaks.search