name: InventoryTweaks
version: 1.3.3
author: IKEA_Jesus
main: dev.w1zzrd.invtweaks.InvTweaksPlugin
api-version: 1.13
depend:
  - WizCompat
commands:
  sort:
    description: Sort chest you are looking at
    usage: /<command>
    permission: invtweaks.sort
  magnet:
    description: Toggle item magnet mode for player
    usage: /<command>
    permission: invtweaks.magnet
  search:
    description: Search for a given item in all nearby inventories
    usage: /<command> {item type}
    permission: invtweaks.search
  capitator:
    description: Toggle tree capitation for an axe in your main hand
    usage: /<command>
    permission: invtweaks.capitator
  chestname:
    description: Add a floating nametag to a chest
    usage: /<command> {name}
    permission: invtweaks.spawnfake